MvcGuestBook/MvcGuestBook/Models/Guestbook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcGuestBook.Models
{
    public class Guestbook
    {
        [Key]
        public int No { get; set; }
        [Required]
        public string Message { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime CreatedOn { get; set; }

        public virtual Member Member { get; set; }

        //[NotMapped]
        //public string FamilyName {
        //    get
        //    {
        //        return this.Name.Substring(0, 1);
        //    }
        //    set
        //    {
        //        this.Name = value.Substring(0, 1) + this.Name.Substring(1);
        //    }
        //}
    }
   //[MetadataType(typeof(MemberMetadata))]
    public class Member
    {
        // private class MemberMetadata
        // {
        public int ID { get; set; }

        [Required]   //加入 [Required] ，將此欄位設為必填欄位
        [MaxLength(5)]
        public string Name { get; set; }

        [MaxLength(200)]
       // [RegularExpression(@"^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1.3}\.| (([\w-]+\.)+))([a-zA-Z]{2,4})$", ErrorMessage = "請輸入正確的Email格式")]
        public string Email { get; set; }

       //[Range(1, 3, ErrorMessage = "請選擇代表圖示")]
       //public int EmotionIcon { get; set; }

        public ICollection<Guestbook> Guestbooks { get; set; }
        //}
    }

}

MvcGuestBook/MvcGuestBook/Controllers/GuestbookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcGuestBook.Models;
using System.ComponentModel.DataAnnotations;

namespace MvcGuestBook.Controllers
{
    public class GuestbookController : Controller
    {
        private MvcGuestBookContext db = new MvcGuestBookContext();

        //
        // GET: /Guestbook/

        public ActionResult Index()
        {
            TempData["temp"] = "tempData可不可以用呢?";
            //ViewBag.test = TempData["temp"];
            TempData["Msg"] = "javascript test";
            return View(db.Guestbooks.ToList());
        }

        public ActionResult Write()
        {
            return View();
        }

        //
        // POST: /Guestbook/Write

        [HttpPost]
        // 會自動將網頁表單中的名稱 對應到 Guestbook 類別中的屬性
        public ActionResult Write(Guestbook guestbook)  
        {
            if (ModelState.IsValid) // 若回傳 false 表示驗證失敗
            {
                guestbook.CreatedOn = DateTime.Parse("2013/07/11");
                db.Guestbooks.Add(guestbook);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(guestbook); // 將網頁的資料再次船回到 View，避免資料遺失
        }

        public ActionResult JavaScriptTest() //會執行兩次!?
        {
            return JavaScript("alert('123')");
        }

        public class GuestbookForm
        {
            [Required]
            public int Type { get; set; }
            [Required]
            public string Name { get; set; }
            [Required]
            public string Email { get; set; }
            [Required]
            public string Body { get; set; }

            public string Logintime { get; set; }
        }


       // [HttpPost]
        public ActionResult TestForm(/*[Bind(Exclude="Logintime")]GuestbookForm gbook*/
            /*FormCollection form*/)
        {
          //  if ( !ModelState.IsValid ) {
          //  return View(); 
          //  }
            //ViewData.Model = form["Confirmedpassword"];
           // return RedirectToAction("Index", "Home");

            //GuestbookForm gbook = new GuestbookForm();
            ////UpdateModel<GuestbookForm>(gbook);
            //if (!TryUpdateModel<GuestbookForm>(gbook))
            //{
            //    // 模型連結發生失敗
            //    return View();
            //}
            
            //return Redirect("/");
            ///////////////////////
            //Dictionary<string, object> attr = new Dictionary<string, object>();
            //attr.Add("size", "16");
            //attr.Add("style", "color:red;");
            //ViewData["Dictionary"] = attr;

            //////////////////////
            List<SelectListItem> listItem = new List<SelectListItem>();
            listItem.Add(new SelectListItem { Text ="是", Value = "1"});
            listItem.Add(new SelectListItem { Text = "否", Value = "0" });

            ViewData["List"] = new SelectList(listItem, "Value", "Text", "");

            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcGuestBook/MvcGuestBook/Views/Guestbook/Index.cshtml
@model IEnumerable<MvcGuestBook.Models.Guestbook>

@{  // 有括號沒括號有差喔!
    ViewBag.Title = "顯示留言";
}

<h2>顯示留言</h2>

<p>
    @Html.ActionLink("留下足跡", "Write")
</p>
<p>
    @Html.ActionLink("表格測試", "TestForm")
</p>
<table>
    <tr>
        <th>
            <font size='5' color='666633'>
            @Html.DisplayNameFor(model => model.Member.Name)
            </font>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Member.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Message)
        </th>
        <th>
           

        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Member.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Member.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Message)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.No }) |
            @Html.ActionLink("Details", "Details", new { id=item.No }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.No })
        </td>
    </tr>
}

</table>
    
    @*<script type="text/javascript">
        var msg = "@TempData["Msg"]"
        if (msg != "")
        { alert(msg); }
      </script>*@

    @{
        var isVaild = true;
        if (isVaild) {
            <text> 有權限! </text>
        }
    }

    @{
        ViewBag.BlogID = "BLOG01";
    }
    <a id = "Link@(ViewBag.BlogID)" href ="http://www.google.com"> test blog</a>

MvcGuestBook/MvcGuestBook/Views/Guestbook/TestForm.cshtml
@{
    ViewBag.Title = "TestFrom";
}

<h2>TestFrom</h2>


@*<form method="post">
    Type 
    <input type="radio" name="Type" value="1" checked="checked" />
    Type1
    <input type="radio" name="Type" value="2" checked="checked" />
    Type2
    <br />

    Name
    <input type="text" id="Name" name="Name" value="" />
    <br />

    Email
    <input type="text" id="Email" name="Email" value="" />
    <br />

    Body
    <textarea cols="20" rows="2" name="Body" id="Body"></textarea>
    <br />

    <input type="submit" />
</form>
*@

@*
@using (Html.BeginForm("Index", "Guestbook", FormMethod.Post))
{
    @Html.Label("Username", "帳號")
    @Html.TextBox("Username", "kevinlin", new { id="testID"})
    <input type ="submit" />
}
*@


@*@{
    var htmlAttribute = ViewData["Dictionary"] as Dictionary<string, object>;
}
@Html.TextBox("Name", "Value", htmlAttribute)
<br />
@Html.Password("Password", "Value", htmlAttribute)
<br />
@Html.TextBox("Email", "Value", htmlAttribute)
<br />
@Html.TextBox("Tel", "Value", htmlAttribute)
<br />
@Html.Hidden("id", "1")
*@

@Html.DropDownList("List", ViewData["Item"] as SelectList, "請選擇")

MvcGuestBook/MvcGuestBook/Views/Guestbook/Write.cshtml
@model MvcGuestBook.Models.Guestbook

@{
    ViewBag.Title = "留下足跡";
}
@TempData["temp"];


<h2>留下足跡</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Guestbook</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Member.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Member.Name)
            @Html.ValidationMessageFor(model => model.Member.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Member.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Member.Email)
            @Html.ValidationMessageFor(model => model.Member.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Message)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Message)
            @Html.ValidationMessageFor(model => model.Message)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

@Ajax.ActionLink("測試JavaScript", "JavaScripttest", new AjaxOptions())

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}